name: Auto-update Charm Libraries
on:
  # Manual trigger
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update-lib:
    name: Check libraries
    uses: canonical/observability/.github/workflows/charm-update-libs.yaml@v0
    secrets: inherit

